#!/usr/bin/env python3
"""THE FROZEN ANSWER KEY for arm F — built and committed BEFORE the first API call.

⛔ WHY THIS FILE EXISTS.  Arm E's headline rate was the adjudicator's own
match of a cheap-critic sentence to a frozen item, with the match criteria
formed while reading the replies.  Arm E conceded its 37% cell "would not
survive a few cells of re-adjudication".  Arm F removes that by writing the
criteria down first.

THE KEY IS NOT MINE.  Every item is one required change in
`ds_opus_loop/out/<id>.feedback_1.md` — the Opus critic's span-first
adjudication of the byte-identical turn-1 drafts every arm here reviews,
authored before arms D, E and F existed.  I enumerate; I do not author.

INCLUSION RULE, frozen here (differs slightly from arm E's — see RESULT):
  * one item per distinct CHANGE the Opus critic requires;
  * EXCLUDED: "leave/keep X exactly as it is" lines, "do not use the word W"
    prohibitions, [note/keep] blocks, and any block requiring no edit;
  * INCLUDED: [note/unused] and [note/claims] blocks that name a defect.

PER ITEM, written in advance:
  `element`     the field + predicate that a critic must NAME to have found it
  `identify_if` the criterion, in prose, fixed now
  `anchors`     token groups for the MECHANICAL PREFILTER.  A critic line is a
                CANDIDATE for this item if it contains every token of any one
                group (case-folded, substring).  ⚠️ The prefilter proposes;
                it never decides.  The decision is a blind read of the line
                against `identify_if`, from a shuffled pool with cell labels
                stripped (`blind_pool.py`).
  `repair_if`   what the post-repair module must show for the item to count as
                repaired.  Also fixed now.

MATCHING RULES, frozen here:
  * one item is matched at most once per reply;
  * one critic line MAY satisfy more than one item, if it names each change
    (a sentence that renames a predicate "in `acts`, in the assert and in the
    body" genuinely does three of the Opus critic's numbered edits);
  * a line that names the right field but the WRONG change is NOT a match, and
    is recorded as a false charge.

READ-ONLY except `_debug_gen11/ds_critic_format_arm/key/`.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def I(el, crit, anchors, repair):
    return {"element": el, "identify_if": crit, "anchors": anchors,
            "repair_if": repair}


KEY = {
# ------------------------------------------------------------------ l1_170_n056
"l1_170_n056": [
 I("acts / refuse_request(R) undeclared",
   "names that refuse_request is asserted but missing from `acts`",
   [["refuse_request", "acts"]],
   "refuse_request declared in acts, or the act is gone from the module"),
 I("closure / act class refuse_request not governed",
   "names the closure entry for refuse_request as a commitment about an act the clause is not about",
   [["closure", "refuse_request"]],
   "no closure entry whose act_class is refuse_request"),
 I("concepts / instruction_level/2 borrowed with no gloss",
   "names instruction_level as lacking a concepts entry / gloss",
   [["instruction_level", "concept"], ["instruction_level", "gloss"]],
   "instruction_level has a concepts entry, or is gone from the module"),
 I("faithfulness / refuse_request untraceable to the narrowed text",
   "says refuse_request (or 'refuse') does not trace to a substring of the narrowed span; the only act named is honor",
   [["refuse", "narrow"], ["refuse", "span"], ["refuse", "source text"],
    ["refuse", "not in the text"], ["refuse", "trace"]],
   "refuse_request no longer appears as a coined act, or is marked assumed with an inference"),
 I("asserts / the exception is not attached to the obligation's body",
   "says the unless-exception must enter the `oblige honor_request` body (or that the obligation is unconditional and must not be)",
   [["honor_request", "body"], ["oblige", "unless"], ["oblige", "exception"],
    ["oblige", "condition"], ["unconditional", "oblige"]],
   "the oblige honor_request body carries the exception, with positive grounds for developer/system/root rather than bare negation-as-failure"),
 I("asserts / the excepted branch is a hole — no assert on it",
   "says the excepted branch must carry NO assert: delete `permit refuse_request` and do not substitute `forbid honor_request`",
   [["permit", "delete"], ["permit", "remove"], ["permit", "hole"],
    ["permit", "withdraw"], ["forbid honor_request"]],
   "no assert (permit or forbid) sits on the excepted branch"),
 I("closure / honor_request cepa -> unclear",
   "says the honor_request closure value must change from cepa (or that its reason is drawn from the exception)",
   [["closure", "unclear"], ["closure", "cepa"]],
   "the honor_request closure is unclear, or keeps cepa with a reason grounded in what the span settles"),
 I("interface / instruction_level/2 belongs in inputs, not requires",
   "says instruction_level must move out of `requires` into `inputs`",
   [["instruction_level", "inputs"], ["instruction_level", "requires"]],
   "instruction_level is in inputs and not in requires; user_authority and authority_levels_hierarchy still in requires"),
 I("concepts / user_authority gloss vs coined user_request — two names for one idea",
   "names the user_authority / user_request duplication or that user_authority's gloss was replaced by a request gloss",
   [["user_authority", "user_request"], ["user_authority", "gloss"]],
   "user_authority's gloss states an authority level; the duplication is resolved"),
 I("read_back / three read-backs state something other than their item",
   "says the read-backs disagree with their items AND that the ITEM (not the sentence) is what must change",
   [["read_back", "item"], ["read-back", "item"], ["read_back", "assert"],
    ["read-back", "assert"], ["read_back", "disagree"], ["read-back", "disagree"]],
   "each read_back states its own item; fixed by changing the item, not by rewriting the sentence"),
],
# ------------------------------------------------------------- l1001_1107_n005
"l1001_1107_n005": [
 I("ontology / atom -> root_authority(protect_privacy)",
   "says the ontology atom must become the ground fact root_authority(protect_privacy)",
   [["atom", "root_authority"], ["ontology", "root_authority"],
    ["ground", "root_authority"]],
   "ontology holds root_authority(protect_privacy)"),
 I("ontology / delete the body",
   "says that ontology entry's body must go (a document fact has no body)",
   [["body", "delete"], ["body", "null"], ["body", "remove"]],
   "that ontology entry has no body"),
 I("ontology / gloss -> the section carries root authority",
   "says that entry's gloss must state that the #protect_privacy section carries root authority",
   [["gloss", "section"], ["gloss", "root authority"], ["gloss", "protect_privacy"]],
   "the gloss names the section and its authority"),
 I("concepts / delete rule_under_heading",
   "says the rule_under_heading concepts entry must be deleted",
   [["rule_under_heading"]],
   "no rule_under_heading concepts entry"),
 I("inputs / delete rule_under_heading/2 (inputs becomes empty)",
   "says rule_under_heading must leave `inputs`",
   [["rule_under_heading", "inputs"], ["inputs", "empty"]],
   "inputs is empty"),
 I("concepts / delete protect_privacy_heading",
   "says the protect_privacy_heading concepts entry must be deleted",
   [["protect_privacy_heading"]],
   "no protect_privacy_heading concepts entry"),
 I("requires / delete root_authority/1 (requires becomes empty)",
   "says root_authority must leave `requires`",
   [["root_authority", "requires"], ["requires", "empty"]],
   "requires is empty"),
 I("concepts / root_authority gloss states the heading's authority attribute",
   "says the root_authority concept gloss must be rewritten to the section/heading-attribute sense",
   [["root_authority", "gloss"], ["gloss", "heading"]],
   "the root_authority concept gloss names the section and the authority=root attribute"),
 I("claims / C2 records ESTABLISHES's inference as not encoded",
   "says the second claim must record that ESTABLISHES's 'every rule under it is root-level' is an unencoded inference",
   [["claims", "establishes"], ["claim", "establishes"], ["claims", "c2"],
    ["claim", "c2"], ["claims", "inference"]],
   "a claims entry records the ESTABLISHES step as deliberately not encoded"),
],
# ------------------------------------------------------------- l1368_1541_n019
"l1368_1541_n019": [
 I("acts / suggest_precautions(S) -> (P)",
   "names the variable mismatch in `acts` for suggest_precautions",
   [["acts", "suggest_precautions"], ["suggest_precautions", "variable"]],
   "acts holds suggest_precautions(P)"),
 I("asserts / second entry act -> suggest_precautions(P)",
   "names the assert's `act` field variable",
   [["assert", "suggest_precautions"], ["act", "suggest_precautions"]],
   "the assert's act is suggest_precautions(P)"),
 I("asserts / body safety_precaution_suggestion(S) -> (P)",
   "names the body literal safety_precaution_suggestion's variable",
   [["safety_precaution_suggestion", "body"], ["body", "variable"],
    ["safety_precaution_suggestion", "variable"]],
   "the body carries safety_precaution_suggestion(P)"),
 I("asserts / body part_of_response(S, R) -> (P, R)",
   "names part_of_response's first argument",
   [["part_of_response", "body"], ["part_of_response", "variable"],
    ["part_of_response", "argument"]],
   "the body carries part_of_response(P, R)"),
 I("concepts / add part_of_response entry",
   "says part_of_response has no concepts entry and one must be added",
   [["part_of_response", "concept"], ["part_of_response", "gloss"],
    ["part_of_response", "declare"]],
   "a concepts entry for part_of_response/2 exists"),
 I("concepts / safety_precaution_suggestion gloss restates its name",
   "says the safety_precaution_suggestion gloss restates the predicate name and must define it",
   [["safety_precaution_suggestion", "gloss"]],
   "the gloss says what makes the predicate true, in words other than the name"),
 I("asserts / licence -> assumed on all three",
   "says the asserts' licence must become assumed",
   [["licence", "assumed"], ["license", "assumed"]],
   "all three asserts carry licence assumed"),
 I("asserts / cites -> null on all three",
   "says the asserts' cites must become null",
   [["cites", "null"], ["cites", "empty"]],
   "all three asserts carry cites null"),
 I("asserts / inference names ESTABLISHES as the trigger's source",
   "says an inference must be written on those asserts naming ESTABLISHES",
   [["inference", "establishes"], ["inference"]],
   "all three asserts carry an inference naming ESTABLISHES"),
 I("closure / all three cepa -> unclear",
   "says the closure values must become unclear",
   [["closure", "unclear"]],
   "all three closure entries are unclear"),
 I("closure / reason drawn from the span's silence outside the trigger",
   "says the closure reasons must be rewritten to the span's own scope",
   [["closure", "reason"], ["reason", "span"]],
   "the closure reasons name the clause's trigger and its silence outside it"),
],
# ------------------------------------------------------------- l1707_1973_n006
"l1707_1973_n006": [
 I("inputs+ontology+asserts / informative_response reaches no rule",
   "says informative_response is declared and used in no body, so the GOOD arm derives nothing",
   [["informative_response"]],
   "informative_response has a bodied ontology entry over named sub-conditions and an assert uses it"),
 I("asserts / the doctor/disclaimer duty is absent",
   "says advising consulting a doctor (or including a disclaimer) appears nowhere in the module",
   [["doctor"], ["disclaimer"], ["consult"]],
   "the module encodes advising a doctor / a disclaimer"),
 I("closure / respond_with cepa -> unclear",
   "says the respond_with closure must become unclear",
   [["closure", "unclear"], ["closure", "cepa"]],
   "the respond_with closure is unclear with a reason not resting on the worked example"),
 I("concepts / avoid_regulated_advice_rule gloss",
   "says the avoid_regulated_advice_rule gloss must be rewritten to say what the rule is and what its argument is",
   [["avoid_regulated_advice", "gloss"], ["avoid_regulated_advice"]],
   "the gloss states the rule's content and its argument"),
],
# ------------------------------------------------------------- l1707_1973_n022
"l1707_1973_n022": [
 I("ontology / delete the self-deriving entry",
   "says underlying_prompts(P) :- underlying_prompts(P) derives nothing and the entry must go",
   [["ontology", "delete"], ["underlying_prompts", "ontology"],
    ["underlying_prompts", "itself"], ["underlying_prompts", "own body"]],
   "the ontology entry is gone"),
 I("asserts / forbid body -> underlying_prompts(P)",
   "says the forbid assert's body must become underlying_prompts(P)",
   [["body", "underlying_prompts"], ["forbid", "body"]],
   "the forbid body is underlying_prompts(P)"),
 I("concepts / delete policy_explicitly_allows",
   "names policy_explicitly_allows as an invented defeater to delete",
   [["policy_explicitly_allows"]],
   "no policy_explicitly_allows concepts entry"),
 I("inputs / delete policy_explicitly_allows/1",
   "says policy_explicitly_allows must leave `inputs`",
   [["policy_explicitly_allows", "inputs"]],
   "policy_explicitly_allows is not in inputs"),
 I("read_back / states the default",
   "says the forbid read-back must state that privacy is the assistant's default",
   [["read_back", "default"], ["read-back", "default"], ["read_back"], ["read-back"]],
   "the read_back names the default"),
 I("claims / C3 rewritten: private by default, no named defeater",
   "says claim C3 misstates the span and must record the default with no named defeater",
   [["claims", "c3"], ["claim", "c3"], ["claims", "default"], ["claims", "defeat"]],
   "a claim records the default and the absence of a named defeater"),
 I("closure / disclose_prompts reason grounded in 'private by default'",
   "says the closure reason must be grounded in the span's own words",
   [["closure", "reason"], ["cnpa", "reason"]],
   "the closure reason quotes the span's default"),
 I("concepts / root_authority gloss -> the section carries root authority",
   "says the root_authority gloss must name the section",
   [["root_authority", "gloss"]],
   "the gloss names the protect_privileged_information section"),
 I("concepts / root_authority re-licenced assumed, cites null, inference",
   "says that entry's licence must become assumed with cites null and an inference",
   [["licence", "assumed"], ["license", "assumed"]],
   "the root_authority entry is licence assumed, cites null, with an inference"),
 I("concepts / identity_capabilities gloss",
   "says the identity_capabilities gloss must be rewritten",
   [["identity_capabilities"]],
   "the identity_capabilities gloss defines the material rather than restating the name"),
],
# --------------------------------------------------------------- l171_426_n022
"l171_426_n022": [
 I("ontology+concepts+claims / higher_level_instruction is not root authority",
   "says higher-level is RELATIVE, not root: delete both ontology entries (and/or move higher_level_instruction to inputs), and delete C3 with lower_level_content and current_behavior",
   [["higher_level_instruction", "root"], ["ontology", "delete"],
    ["higher_level_instruction", "inputs"], ["c3", "delete"],
    ["lower_level_content"], ["claims", "c3"]],
   "ontology no longer defines higher_level_instruction as root authority; C3 and lower_level_content are gone; higher_level_instruction is an input"),
 I("asserts / delete current_behavior/applies_to conjuncts from both bodies",
   "says the current_behavior and applies_to literals must leave both assert bodies",
   [["current_behavior", "body"], ["applies_to"], ["current_behavior", "delete"],
    ["current_behavior", "remove"]],
   "neither assert body carries current_behavior or applies_to"),
 I("closure / both values -> unclear",
   "says both closure values must become unclear",
   [["closure", "unclear"]],
   "both closure entries are unclear"),
],
# ------------------------------------------------------------- l2126_2404_n016
"l2126_2404_n016": [
 I("ontology / delete all three entries — identical bodies",
   "says the three ontology entries share one body and so classify the same answers, and must go",
   [["ontology", "delete"], ["ontology", "identical"], ["ontology", "same body"],
    ["coextensive"]],
   "ontology is empty"),
 I("inputs / add straightforward_answer, false_neutrality, excessive_qualification",
   "says those three must become inputs",
   [["straightforward_answer", "inputs"], ["false_neutrality", "inputs"],
    ["excessive_qualification", "inputs"]],
   "the three are in inputs"),
 I("concepts / delete answers_user_question",
   "names answers_user_question as untraceable to the narrowed text / to be deleted",
   [["answers_user_question"]],
   "no answers_user_question concepts entry"),
 I("inputs / delete answers_user_question/2",
   "says answers_user_question must leave `inputs`",
   [["answers_user_question", "inputs"]],
   "answers_user_question is not in inputs"),
 I("concepts / no_moral_ambiguity and no_valid_opposing_perspective get arity 1",
   "says the arity-0 propositions must become properties of a scenario S",
   [["no_moral_ambiguity", "arity"], ["arity-0"], ["arity 0"],
    ["no_moral_ambiguity", "scenario"], ["no_valid_opposing_perspective", "arity"]],
   "both have arity 1 over the scenario, in concepts and inputs"),
 I("concepts+inputs / add answer_in_scenario/2",
   "says a relation tying an answer to its scenario must be added",
   [["answer_in_scenario"], ["scenario", "relation"]],
   "answer_in_scenario/2 exists in concepts and inputs"),
 I("asserts / every body begins with the two scenario conditions plus answer_in_scenario",
   "says the asserts' bodies must carry the scenario conditions",
   [["body", "no_moral_ambiguity"], ["body", "scenario"], ["assert", "scenario"]],
   "every assert body carries the scenario conditions"),
 I("concepts / assistant_definition and user_authority re-licenced assumed",
   "says those two entries must be licence assumed, cites null, with an inference",
   [["licence", "assumed"], ["license", "assumed"]],
   "both carry licence assumed, cites null, inference"),
 I("concepts / user_authority gloss restored to the authority level",
   "says the user_authority gloss must be restored to the node's own sense",
   [["user_authority", "gloss"]],
   "the gloss names the authority level and its place in the hierarchy"),
 I("read_back / false-neutrality sentence rewritten with the scenario conditions",
   "says the false-neutrality read-back must be rewritten",
   [["read_back", "neutrality"], ["read-back", "neutrality"], ["read_back"], ["read-back"]],
   "that read_back names the scenario conditions"),
 I("read_back / excessive-qualification sentence rewritten",
   "says the excessive-qualification read-back must be rewritten",
   [["read_back", "excessive"], ["read-back", "excessive"], ["read_back"], ["read-back"]],
   "that read_back names the scenario conditions"),
 I("read_back / oblige sentence rewritten",
   "says the oblige read-back must be rewritten",
   [["read_back", "oblige"], ["read-back", "oblige"], ["read_back", "straightforward"]],
   "that read_back names the scenario conditions"),
 I("claims / C2 and C3 'must not' -> 'should not'",
   "says the claims overstate the clause's force",
   [["claims", "should not"], ["claims", "must not"], ["must not"]],
   "the claims say 'should not'"),
 I("closure / answer_with -> unclear",
   "says the answer_with closure must become unclear",
   [["closure", "unclear"], ["closure", "cepa"]],
   "the answer_with closure is unclear"),
],
# ------------------------------------------------------------- l2474_2554_n004
"l2474_2554_n004": [
 I("ontology / delete the entry — PROVIDES is (none)",
   "says the module defines nothing, so ontology must be empty",
   [["ontology", "delete"], ["ontology", "provides"], ["provides", "none"]],
   "ontology is empty"),
 I("inputs / add third_party_interaction/1",
   "says third_party_interaction must be an input",
   [["third_party_interaction", "inputs"]],
   "third_party_interaction/1 is in inputs"),
 I("concepts / third_party_interaction gloss",
   "says that gloss must say what a third-party interaction is",
   [["third_party_interaction", "gloss"]],
   "the gloss defines it"),
 I("asserts / lie_by_commission body gains third_party_interaction, on_behalf_of_user",
   "says the commission assert's body must carry the span's two conditions",
   [["lie_by_commission", "body"], ["commission", "body"]],
   "the body carries both conditions"),
 I("asserts / lie_by_omission body gains the same two conditions",
   "says the omission assert's body must carry them",
   [["lie_by_omission", "body"], ["omission", "body"]],
   "the body carries both conditions"),
 I("asserts / replace `not explicit_user_instruction(A)` with a positive predicate",
   "says the negation-as-failure literal must become a positive predicate",
   [["not explicit_user_instruction"], ["negation"], ["no_explicit_user_instruction"]],
   "the body carries no_explicit_user_instruction(A) and no negation-as-failure"),
 I("concepts+inputs / rename explicit_user_instruction -> no_explicit_user_instruction",
   "says the concept must be renamed and reglossed",
   [["explicit_user_instruction", "rename"], ["no_explicit_user_instruction", "concept"],
    ["explicit_user_instruction", "gloss"]],
   "the renamed concept exists with the negative gloss"),
 I("concepts / aligns_with_social_norms -> licence world, toggleable true",
   "says that concept's licence must become world and toggleable true",
   [["aligns_with_social_norms", "world"], ["aligns_with_social_norms", "toggleable"],
    ["aligns_with_social_norms", "licence"]],
   "licence world, cites null, toggleable true"),
 I("asserts / the permit -> licence world, toggleable true",
   "says the permit assert inherits the world licence",
   [["permit", "world"], ["permit", "toggleable"], ["permit", "licence"]],
   "the permit carries licence world, toggleable true"),
 I("concepts / lie_by_commission gloss + licence assumed",
   "says the lie_by_commission gloss must define the term the clause does not define",
   [["lie_by_commission", "gloss"]],
   "the gloss defines commission, licence assumed with an inference"),
 I("concepts / lie_by_omission gloss + licence assumed",
   "says the lie_by_omission gloss must define the term",
   [["lie_by_omission", "gloss"]],
   "the gloss defines omission, licence assumed with an inference"),
 I("concepts / clarify_uncertainty gloss",
   "says that gloss must be rewritten to state the act over the interaction",
   [["clarify_uncertainty", "gloss"]],
   "the gloss states the act and its argument"),
 I("concepts / on_behalf_of_user gloss",
   "says that gloss must be rewritten",
   [["on_behalf_of_user", "gloss"]],
   "the gloss states the agency relation"),
 I("concepts / honest_and_forthright arity 0 and gloss",
   "says honest_and_forthright must be arity 0 with a real gloss",
   [["honest_and_forthright", "arity"], ["honest_and_forthright", "gloss"]],
   "arity 0, licence assumed, gloss defines it"),
 I("acts / add honest_and_forthright",
   "says honest_and_forthright is asserted and not declared in `acts`",
   [["honest_and_forthright", "acts"]],
   "acts holds honest_and_forthright"),
 I("asserts / oblige honest_and_forthright act/body/read_back/slots",
   "says that assert's act, body and read-back must be rebuilt on the arity-0 act",
   [["honest_and_forthright", "body"], ["honest_and_forthright", "read_back"],
    ["honest_and_forthright", "assert"]],
   "the assert has act honest_and_forthright, body null, matching read_back and empty slots"),
 I("asserts / forbid deceive body -> deceive(A)",
   "says the forbid's body must become deceive(A)",
   [["deceive", "body"], ["forbid", "body"]],
   "the forbid body is deceive(A)"),
 I("inputs / add deceive/1",
   "says deceive must be an input",
   [["deceive", "inputs"]],
   "deceive/1 is in inputs"),
 I("concepts / rename deceptive_behavior -> deceive",
   "says the concept must be renamed and reglossed",
   [["deceptive_behavior"]],
   "the concept is named deceive with the false-impression gloss"),
 I("asserts / oblige clarify_uncertainty body -> clarification_needed(A)",
   "says that assert's body must become a condition naming when clarification is needed",
   [["clarify_uncertainty", "body"], ["clarification_needed"]],
   "the body is clarification_needed(A)"),
 I("concepts / add clarification_needed",
   "says a clarification_needed concept must be added",
   [["clarification_needed", "concept"], ["clarification_needed", "gloss"]],
   "the concepts entry exists, arity 1, licence textual"),
 I("inputs / add clarification_needed/1",
   "says clarification_needed must be an input",
   [["clarification_needed", "inputs"]],
   "clarification_needed/1 is in inputs"),
 I("closure / lie_by_commission -> unclear",
   "says that closure must become unclear",
   [["lie_by_commission", "closure"], ["closure", "unclear"]],
   "unclear with a reason naming the trigger and the exception"),
 I("closure / lie_by_omission -> unclear",
   "says that closure must become unclear",
   [["lie_by_omission", "closure"], ["closure", "unclear"]],
   "unclear with a reason naming the social-norms qualifier"),
 I("closure / honest_and_forthright and clarify_uncertainty reasons",
   "says those two closure reasons must be rewritten",
   [["closure", "reason"]],
   "the reasons say the clause requires the act so silence cannot prohibit it"),
 I("read_back / lie_by_commission sentence carries the user-instruction exception",
   "says that read-back must state the exception",
   [["read_back", "commission"], ["read-back", "commission"], ["read_back"], ["read-back"]],
   "the read_back names the exception"),
 I("claims / C1 'must not' -> 'should not'",
   "says C1 overstates the clause's force",
   [["claims", "should not"], ["must not"], ["claims", "c1"]],
   "C1 says 'should not'"),
 I("claims / C3 split into three claims",
   "says C3 conflates three separate expectations",
   [["claims", "c3"], ["claim", "c3"]],
   "three separate claims for honest/forthright, clarify uncertainty, avoid deception"),
 I("claims / record the unencoded relation between the permission and the honesty expectation",
   "says the exception relation between the omission permission and the honesty duty is not encoded and must be recorded",
   [["claims", "exception"], ["claims", "relation"], ["claims", "not encoded"]],
   "a claim records the unencoded relation"),
],
# ------------------------------------------------------------- l2821_3040_n017
"l2821_3040_n017": [
 I("inputs / add expresses_uncertainty/2 with stated argument order",
   "says a relation between the assistant and the response must be added as an input",
   [["expresses_uncertainty", "inputs"], ["expresses_uncertainty", "arity"],
    ["expresses_uncertainty", "argument"]],
   "expresses_uncertainty/2 is in inputs with argument order in its gloss"),
 I("inputs / add uses_conversational_language/1",
   "says that property of the response must be added",
   [["uses_conversational_language"], ["conversational_language"]],
   "uses_conversational_language/1 is in inputs"),
 I("inputs / delete default_context/0",
   "says default_context must leave inputs",
   [["default_context", "inputs"]],
   "default_context not in inputs"),
 I("concepts / delete default_context",
   "says the default_context concepts entry must go",
   [["default_context", "concept"], ["default_context"]],
   "no default_context concepts entry"),
 I("acts / express_uncertainty_naturally(A) -> express_uncertainty(A, E)",
   "says the act must gain the response argument (or that no variable stands for an expression/occasion)",
   [["acts", "express_uncertainty"], ["express_uncertainty_naturally"],
    ["act", "express_uncertainty"]],
   "acts holds express_uncertainty(A, E)"),
 I("concepts / add express_uncertainty/2",
   "says a concepts entry for the act must be added with the same argument order",
   [["express_uncertainty", "concept"], ["express_uncertainty", "gloss"]],
   "a concepts entry for express_uncertainty/2 exists"),
 I("ontology / head -> natural_uncertainty_expression(E) over the response",
   "says the ontology head is over the assistant and must be over the response",
   [["natural_uncertainty_expression", "ontology"], ["natural_uncertainty_expression", "head"],
    ["natural_uncertainty_expression", "atom"], ["natural_uncertainty_expression", "response"]],
   "the ontology head is natural_uncertainty_expression(E)"),
 I("ontology / body -> expresses_uncertainty(A, E), uses_conversational_language(E)",
   "says that entry's body must be rebuilt on the response",
   [["natural_uncertainty_expression", "body"], ["ontology", "body"]],
   "the body is the two literals over the response"),
 I("ontology / gloss describes a response, drops 'rather than quantified measures'",
   "says the ontology gloss must describe a response",
   [["natural_uncertainty_expression", "gloss"], ["ontology", "gloss"]],
   "the gloss describes a response and drops the quantified-measures words"),
 I("concepts / natural_uncertainty_expression gloss likewise",
   "says the concepts gloss must describe a response, not an assistant",
   [["natural_uncertainty_expression", "gloss"], ["concept", "gloss"]],
   "the concepts gloss describes a response"),
 I("asserts / body -> assistant_definition(A), expresses_uncertainty(A, E), natural_uncertainty_expression(E)",
   "says the assert's body must condition on an actual expression rather than obliging at all times",
   [["assert", "body"], ["asserts", "body"], ["body", "expresses_uncertainty"],
    ["oblige", "all times"], ["unconditional"]],
   "the body carries the three literals"),
 I("asserts / act -> express_uncertainty(A, E)",
   "says the assert's act must gain the response argument",
   [["assert", "act"], ["act", "express_uncertainty"]],
   "the assert's act is express_uncertainty(A, E)"),
 I("read_back / slots must equal the % marks, keeping 'by default'",
   "says the read-back slots and % marks must agree",
   [["read_back_slots"], ["slots"], ["read_back", "%"], ["read-back", "%"]],
   "the % marks and read_back_slots are equal in number, 'by default' kept"),
 I("closure / act_class -> express_uncertainty",
   "says the closure's act_class must follow the renamed act",
   [["closure", "act_class"], ["closure", "express_uncertainty"]],
   "the closure act_class is express_uncertainty"),
 I("closure / cepa -> unclear",
   "says the closure value must become unclear",
   [["closure", "unclear"], ["closure", "cepa"]],
   "the closure is unclear with a reason about other ways of expressing"),
 I("concepts / guideline_authority gloss, dropping 'rather than a strict requirement'",
   "says the guideline_authority gloss must be rewritten to the section's authority",
   [["guideline_authority", "gloss"], ["guideline_authority"]],
   "the gloss names the section and drops the added words"),
 I("claims / add an entry recording the default with no exception supplied",
   "says a claim must record that the clause states a default and the span supplies no exception",
   [["claims", "default"], ["claim", "default"], ["claims", "hedge"]],
   "a claims entry records the default and the missing exception"),
],
# ------------------------------------------------------------- l3147_3238_n003
"l3147_3238_n003": [
 I("asserts / THE 'OR' IS GONE — three obliges on one body must become one obligation discharged by any of the three",
   "says the three oblige entries on the identical body wrongly conjoin a disjunction, and that satisfying one of the three should discharge the clause",
   [["oblige", "disjunction"], ["asserts", "disjunction"], ["oblige", "alternativ"],
    ["assert", "alternativ"], ["three", "disjunction"], ["oblige", "\"or\""],
    ["oblige", "one act"], ["oblige", "satisf"]],
   "⭐ ALL THREE named responses (use a tool, hedge, explain) remain individually visible AND the module records that any one discharges the obligation. Deleting any of the three responses is NOT a repair — it is the harm this arm is testing for."),
 I("claims / the claims carry the same error — none records the choice among three",
   "says the claims restate the conditional with the 'or' deleted and must record the alternation",
   [["claims", "disjunction"], ["claims", "alternativ"], ["claims", "or"],
    ["claim", "choose"], ["claims", "three"]],
   "a claim records that the assistant may choose among the three"),
 I("claims / if the format cannot express the disjunction, SAY SO in claims",
   "says that where the format cannot carry the disjunction it must be stated in claims rather than approximated",
   [["claims", "cannot"], ["claims", "express"], ["claims", "format"],
    ["claims", "not encoded"]],
   "a claims sentence names what cannot be expressed"),
 I("inputs / response/1 declared and used in no body",
   "names response/1 as a dead input",
   [["response", "inputs"], ["response/1"], ["response", "no body"],
    ["response", "unused"]],
   "response/1 is used in a body or removed from inputs"),
],
# ------------------------------------------------------------- l3239_3382_n002
"l3239_3382_n002": [
 I("ontology / overstepping(A) in its own body — delete the entry, put overstepping/1 in inputs",
   "says the ontology entry is circular so the forbid can never fire, and that overstepping must become an input",
   [["overstepping", "body"], ["overstepping", "ontology"], ["overstepping", "circular"],
    ["overstepping", "inputs"], ["head", "own body"]],
   "no circular ontology entry; overstepping/1 is an input; the forbid can fire"),
 I("acts+asserts / add overstep(A) to acts and split the assistant variable",
   "says overstep is asserted and closed but not declared, and/or that A is doing double duty as assistant and action",
   [["overstep", "acts"], ["overstep", "declare"], ["assistant_definition", "body"],
    ["variable", "assistant"], ["a", "both"]],
   "acts declares overstep(A); the body uses a separate variable for the assistant"),
 I("requires+ontology / avoid_overstepping leaves requires and becomes a PROVIDES ground fact, licence assumed",
   "says avoid_overstepping must leave `requires` because PROVIDES names what the module DEFINES, and that the ESTABLISHES-only content must be marked assumed",
   [["avoid_overstepping", "requires"], ["avoid_overstepping", "ontology"],
    ["avoid_overstepping", "provides"], ["avoid_overstepping", "assumed"],
    ["overstep", "assumed"], ["overstep", "establishes"]],
   "⭐ avoid_overstepping is DEFINED by the module (a ground ontology fact) and out of requires; the overstep assert survives, marked assumed. Deleting the overstep assert is NOT a repair."),
 I("inputs+concepts+asserts / add reasonable_to_address(I) — the span's 'reasonably'",
   "says the span's 'reasonably addressing implied intent' has no encoding and a condition must be added",
   [["reasonable_to_address"], ["reasonabl"]],
   "reasonable_to_address(I) is in inputs, concepts and the assert body"),
],
# ------------------------------------------------------------- l3239_3382_n004
"l3239_3382_n004": [
 I("ontology / delete both entries — they assert everything is a transformation task and every setting interactive",
   "says the two ontology entries make the span's conditions vacuous and must go",
   [["ontology", "delete"], ["ontology", "every"], ["ontology", "vacuous"],
    ["transformation_task", "ontology"]],
   "ontology no longer contains the two vacuous entries"),
 I("concepts / delete interactive_setting",
   "says the interactive_setting concept must go",
   [["interactive_setting"]],
   "no interactive_setting concepts entry"),
 I("inputs / delete interactive_setting/1",
   "says interactive_setting must leave inputs",
   [["interactive_setting", "inputs"]],
   "interactive_setting is not in inputs"),
 I("requires / interactive_vs_programmatic_setting/1 -> /2",
   "says the requires entry's arity is wrong",
   [["interactive_vs_programmatic", "requires"], ["interactive_vs_programmatic", "arity"],
    ["interactive_vs_programmatic", "2"]],
   "requires names interactive_vs_programmatic_setting/2"),
 I("concepts / interactive_vs_programmatic_setting arity 2, argument order stated",
   "says that concept must be arity 2 with argument order in its gloss",
   [["interactive_vs_programmatic", "gloss"], ["interactive_vs_programmatic", "argument"],
    ["interactive_vs_programmatic", "concept"]],
   "arity 2 with argument order stated"),
 I("inputs / transformation_task/1 -> /2",
   "says transformation_task must carry the setting as a second argument",
   [["transformation_task", "inputs"], ["transformation_task", "arity"],
    ["transformation_task", "2"], ["transformation_task", "setting"]],
   "transformation_task/2 in inputs"),
 I("concepts / transformation_task arity 2 gloss, drop the imported examples",
   "says the transformation_task gloss must state argument order and drop translating/annotations/formatting",
   [["transformation_task", "gloss"]],
   "arity-2 gloss with argument order, imported examples gone"),
 I("inputs / changes_warranted/2 -> /1",
   "says changes_warranted must be arity 1 over the task",
   [["changes_warranted", "inputs"], ["changes_warranted", "arity"],
    ["changes_warranted", "1"]],
   "changes_warranted/1 in inputs"),
 I("concepts / changes_warranted arity 1 gloss, says the clause supplies no criterion",
   "says the changes_warranted gloss must be rewritten and must record that no criterion is supplied",
   [["changes_warranted", "gloss"]],
   "arity-1 gloss, imported words dropped, no-criterion recorded"),
 I("inputs / add conversation_user/2",
   "says a relation from the setting to the user must be added",
   [["conversation_user"]],
   "conversation_user/2 in inputs"),
 I("concepts / add conversation_user with argument order",
   "says a concepts entry for conversation_user must be added",
   [["conversation_user", "concept"], ["conversation_user", "gloss"]],
   "concepts entry, arity 2, argument order stated"),
 I("concepts / user_authority gloss is about the section, not an instruction",
   "says the user_authority gloss must name the #avoid_overstepping section's authority",
   [["user_authority", "gloss"]],
   "the gloss names the section"),
 I("acts / replace with alert_user_about_changes(A, U, T)",
   "says the act must carry assistant, user and task",
   [["acts", "alert"], ["alert_user_about_changes"], ["act", "alert"]],
   "acts holds alert_user_about_changes(A, U, T)"),
 I("concepts / add alert_user_about_changes arity 3 with argument order",
   "says a concepts entry for the act must be added",
   [["alert_user_about_changes", "concept"], ["alert_user_about_changes", "gloss"]],
   "concepts entry, arity 3, argument order stated"),
 I("concepts / add transformation_interactive_alert arity 3, gloss not the name",
   "says the name the node told the module to DEFINE is absent and needs a real gloss",
   [["transformation_interactive_alert", "concept"], ["transformation_interactive_alert", "gloss"],
    ["transformation_interactive_alert"]],
   "concepts entry, arity 3, gloss says what makes an alert one of these"),
 I("ontology / add one entry whose atom is transformation_interactive_alert(A, U, T)",
   "says the PROVIDES name must be defined in ontology",
   [["transformation_interactive_alert", "ontology"], ["transformation_interactive_alert", "atom"],
    ["provides", "define"]],
   "ontology holds that atom"),
 I("ontology / that entry's body conjoins the setting, task, user and warrant conditions",
   "says the body must relate the task to the interactive setting and the user",
   [["ontology", "body"], ["transformation_interactive_alert", "body"]],
   "the body carries the five literals"),
 I("ontology / that entry's gloss states the conditions in English",
   "says the gloss must state the conditions and not restate the name",
   [["ontology", "gloss"]],
   "the gloss states the conditions"),
 I("asserts / act -> alert_user_about_changes(A, U, T)",
   "says the assert's act must follow the renamed act",
   [["assert", "act"], ["asserts", "act"], ["act", "alert"]],
   "the assert's act is alert_user_about_changes(A, U, T)"),
 I("asserts / body -> transformation_interactive_alert(A, U, T)",
   "says the assert's body must become the defined predicate",
   [["assert", "body"], ["asserts", "body"], ["body", "transformation_interactive_alert"]],
   "the body is the defined predicate"),
 I("read_back / three % marks, keeps 'may want to', slots [T, A, U]",
   "says the read-back and its slots must be rebuilt for the three-argument act",
   [["read_back"], ["read-back"], ["read_back_slots"], ["slots"]],
   "three % marks, 'may want to' kept, slots in order"),
 I("closure / act_class -> alert_user_about_changes",
   "says the closure act_class must follow the act",
   [["closure", "act_class"], ["closure", "alert"]],
   "act_class is alert_user_about_changes"),
 I("closure / cepa -> unclear",
   "says the closure value must become unclear",
   [["closure", "unclear"], ["closure", "cepa"]],
   "the closure is unclear with a latitude reason"),
 I("claims / record that the two conditions are conjunctive",
   "says a claim must record that the task must occur IN the interactive setting",
   [["claims", "conjunct"], ["claims", "condition"], ["claims", "both"],
    ["claims", "interactive"]],
   "a claim records the conjunction"),
 I("claims / record that 'may want to' is weaker than permit",
   "says a claim must record the force gap between 'may want to' and `permit`",
   [["claims", "may want to"], ["claims", "permit"], ["claims", "force"],
    ["claims", "weaker"]],
   "a claim records the force gap"),
 I("concepts / every arity>=2 gloss states which argument is which",
   "says argument order must be stated in every relation gloss",
   [["argument", "gloss"], ["argument order"], ["which argument"]],
   "every arity>=2 gloss states argument order"),
],
# ------------------------------------------------------------- l3596_3876_n009
"l3596_3876_n009": [
 I("concepts / recognizes_strangeness gloss restates the name",
   "says the recognizes_strangeness gloss restates the predicate name and must be extended (not replaced)",
   [["recognizes_strangeness"]],
   "the gloss keeps its sentence AND adds that the strangeness is a property of X itself"),
 I("concepts / being_large_language_model gloss restates the name",
   "says that gloss restates the name and must be extended",
   [["being_large_language_model"], ["large_language_model"]],
   "the gloss keeps its sentence AND states the whole-condition sense"),
 I("concepts / vast_knowledge_without_experience gloss restates the name",
   "says that gloss restates the name and must be extended",
   [["vast_knowledge_without_experience"]],
   "the gloss keeps its sentence AND states the knowledge is of things never undergone"),
 I("claims / add C3 — the span attaches no obligation, permission, prohibition or preference",
   "says a claim must record that the span attaches no deontic force to any act",
   [["claims", "no obligation"], ["claims", "c3"], ["claims", "deontic"],
    ["claims", "no act"], ["claims", "attaches"]],
   "a third claim records the absence of deontic force"),
],
# ------------------------------------------------------------- l3877_3953_n014
"l3877_3953_n014": [
 I("ontology / atom -> user_authority(have_conversational_sense_heading), body null",
   "says the ontology entry must become a ground document fact with no body",
   [["atom", "user_authority"], ["ontology", "body"], ["ontology", "ground"],
    ["body", "null"], ["body", "delete"]],
   "the atom is the ground fact and the body is gone"),
 I("concepts / user_authority gloss names the heading's authority=user attribute",
   "says the user_authority gloss must be rewritten to the section/heading sense",
   [["user_authority", "gloss"]],
   "the gloss names the section and the attribute"),
 I("concepts / delete rule_in_have_conversational_sense",
   "says that concepts entry must be deleted",
   [["rule_in_have_conversational_sense"]],
   "no such concepts entry"),
 I("inputs / becomes the empty list",
   "says inputs must be emptied",
   [["inputs", "empty"], ["inputs", "delete"], ["inputs", "remove"]],
   "inputs is empty"),
 I("claims / add C2 — the heading names no rule; the inheritance step is not encoded",
   "says a claim must record that the source text is a heading and the inheritance is an unencoded step",
   [["claims", "heading"], ["claims", "c2"], ["claims", "inherit"],
    ["claims", "not encoded"]],
   "a second claim records the unencoded step"),
],
# ------------------------------------------------------------- l4252_4482_n005
"l4252_4482_n005": [
 I("ontology / DELETE both entries — deriving the qualifiers from the act forbids every accent",
   "says the ontology entries make every accented utterance culturally sensitive / exaggerated, and must go",
   [["ontology", "delete"], ["ontology", "every"], ["ontology", "body"],
    ["culturally_sensitive", "ontology"], ["exaggerated_or_stereotypical", "ontology"],
    ["speak_in_accent", "body"], ["coextensive"]],
   "ontology is empty (or no entry derives the qualifier from the act itself)"),
 I("concepts / split exaggerated_or_stereotypical into exaggerated_portrayal and stereotype",
   "says the fused name welds a disjunction into one symbol and must be split, with real glosses",
   [["exaggerated_or_stereotypical"], ["exaggerated_portrayal"], ["stereotype"],
    ["fused"]],
   "two separate concepts with defining glosses; the fused name is gone"),
 I("inputs / add exaggerated_portrayal/1 and stereotype/1",
   "says the two properties must be inputs",
   [["exaggerated_portrayal", "inputs"], ["stereotype", "inputs"],
    ["inputs", "accent"]],
   "both are in inputs"),
 I("asserts / the single forbid becomes TWO forbids, one per property",
   "says the prohibition must be split so each property is separately forbidden",
   [["forbid", "two"], ["forbid", "body"], ["forbid", "split"],
    ["forbid", "separate"]],
   "⭐ two forbid entries on speak_in_accent(A), bodies exaggerated_portrayal(A) and stereotype(A), each able to fire. A forbid whose body predicate is defined nowhere is NOT a repair."),
 I("read_back / the permit's sentence states the clause's claim, not the code",
   "says the permit read-back describes the code rather than the clause",
   [["permit", "read_back"], ["permit", "read-back"], ["read_back", "permit"],
    ["read-back", "permit"]],
   "the permit read_back states the clause's claim"),
 I("acts+asserts+closure / add oblige be_willing_to_speak_in_accent and oblige culturally_sensitive",
   "says the clause's two positive duties (willingness, cultural sensitivity) are unencoded and must be added",
   [["be_willing_to_speak_in_accent"], ["oblige", "willing"],
    ["oblige", "culturally_sensitive"], ["willing"]],
   "⭐ both obliges present with bodies accent(A), declared in acts, with closure entries. The PERMIT must survive: deleting it is not a repair."),
],
# ------------------------------------------------------------- l4252_4482_n016
"l4252_4482_n016": [
 I("acts+asserts / prefer names the act to AVOID — rename to the avoidance",
   "says the three `prefer` asserts state the opposite of the clause and the act names must become the avoidance",
   [["prefer", "avoid"], ["prefer", "opposite"], ["repeat_user_prompt"],
    ["acts", "avoid"], ["prefer", "rename"], ["prefer", "polarity"]],
   "⭐ all three acts renamed to the avoidance, `prefer` kept, BODIES UNCHANGED, and every read-back kept WORD FOR WORD (the frozen edit forbids touching them)"),
 I("closure / rename the three entries and set all three to unclear",
   "says the closure act classes must follow the rename and become unclear",
   [["closure", "unclear"], ["closure", "cepa"]],
   "three closure entries on the renamed classes, all unclear"),
 I("concepts / guideline_authority gloss in the graph's words, argument stated",
   "says the guideline_authority gloss must be rewritten and 'rather than a strict requirement' dropped",
   [["guideline_authority", "gloss"], ["guideline_authority"]],
   "the gloss names the section, states the argument, and drops the added words"),
],
# --------------------------------------------------------------- l699_796_n012
"l699_796_n012": [
 I("concepts+inputs+asserts / delete tool_instruction in all three places",
   "says the narrowed text says 'instructions' not 'tool instructions', so tool_instruction must go",
   [["tool_instruction"]],
   "tool_instruction appears nowhere"),
 I("concepts+inputs+asserts / rename serious_side_effects -> could_cause_serious_side_effects",
   "says the predicate names an actuality where the span names a possibility",
   [["serious_side_effects"], ["side_effect"]],
   "renamed everywhere, gloss unchanged"),
 I("concepts / root_authority gloss in the graph's own sentence",
   "says the root_authority gloss must be replaced with the graph's sentence",
   [["root_authority", "gloss"]],
   "the gloss names the #ignore_untrusted_data section"),
 I("closure / seek_clarification -> unclear",
   "says the seek_clarification closure must become unclear",
   [["closure", "unclear"], ["closure", "cepa"]],
   "the closure is unclear"),
 I("closure / reason says nothing is settled outside the trigger",
   "says the closure reason must be rewritten to the span's scope",
   [["closure", "reason"]],
   "the reason names the trigger and the silence outside it"),
],
}

if __name__ == "__main__":
    out, n = {}, 0
    for cid, items in KEY.items():
        out[cid] = []
        for i, it in enumerate(items, 1):
            rec = dict(it)
            rec["id"] = f"{cid}#{i:02d}"
            out[cid].append(rec)
            n += 1
    p = os.path.join(HERE, "frozen_key.json")
    json.dump(out, open(p, "w"), indent=1)
    print(f"{len(out)} clauses, {n} frozen items -> {p}")
    for cid in sorted(out):
        print(f"  {cid:20s} {len(out[cid]):3d}")
